import { FormEvent, useEffect, useState } from 'react';
import { api } from './api/client';
import type { Bootstrap, Chapter, Section, Series, Shelf } from './model/types';

type View='home'|'shelf'|'series'|'learn';

export default function App(){
  const [data,setData]=useState<Bootstrap|null>(null), [view,setView]=useState<View>('home');
  const [shelf,setShelf]=useState<Shelf|null>(null), [series,setSeries]=useState<Series|null>(null), [section,setSection]=useState<Section|null>(null);
  const [busy,setBusy]=useState(''), [error,setError]=useState('');
  useEffect(()=>{api.bootstrap().then(setData).catch(e=>setError(e.message))},[]);
  const run=async<T,>(label:string,fn:()=>Promise<T>)=>{setBusy(label);setError('');try{return await fn()}catch(e){setError(e instanceof Error?e.message:'操作失败');throw e}finally{setBusy('')}};
  const openShelf=(item:Shelf)=>{setShelf(item);setView('shelf')};
  const openSeries=async(id:string)=>{const value=await run('读取系列…',()=>api.series(id));setSeries(value);setView('series')};
  const openChapter=async(chapter:Chapter)=>{const updated=await run('正在规划本章小节…',()=>api.chapter(chapter.id));setSeries(current=>current?{...current,books:current.books.map(b=>({...b,chapters:b.chapters.map(c=>c.id===updated.id?updated:c)}))}:current)};
  const openSection=async(id:string)=>{let value=await run('正在读取小节…',()=>api.section(id));if(!value.content){try{value=await run('正在核查来源并生成本节…',()=>api.generateSection(id))}catch{value=await api.section(id)}}setSection(value);setView('learn')};
  return <><header><button className="brand" onClick={()=>setView('home')}><span>s</span>slow</button><small>{busy||'一步一步，学成自己的书'}</small></header><main>{error&&<div className="error">{error}</div>}{view==='home'&&<Home data={data} onOpen={openShelf}/>} {view==='shelf'&&shelf&&<ShelfPage shelf={shelf} onCreate={async body=>{const value=await run('AI 正在规划系列…',()=>api.createPlan({...body,shelfId:shelf.id}));setSeries(value);setView('series')}} onOpen={openSeries}/>} {view==='series'&&series&&<SeriesPage value={series} onChapter={openChapter} onSection={openSection} onRefresh={()=>openSeries(series.id)}/>} {view==='learn'&&section&&<Reader value={section} onChange={setSection} onBack={()=>{setView('series');series&&openSeries(series.id)}}/>}</main></>;
}

function Home({data,onOpen}:{data:Bootstrap|null;onOpen:(s:Shelf)=>void}){return <section><p className="eyebrow">AI 时代的个人学习书架</p><h1>我的书架</h1><p className="lead">一本书是一个台阶。慢一点，真正理解、验证并留下自己的笔记。</p><div className="shelf-grid">{data?.shelves.map(s=><button className="shelf" key={s.id} onClick={()=>onOpen(s)}><b>{s.name}</b><span>{s.domain} · {s.specialty}</span><small>{s.series.length} 个学习系列</small><i>→</i></button>)}</div></section>}

function ShelfPage({shelf,onCreate,onOpen}:{shelf:Shelf;onCreate:(b:object)=>Promise<void>;onOpen:(id:string)=>void}){
  const [show,setShow]=useState(false);
  return <section><p className="eyebrow">{shelf.domain} · {shelf.specialty}</p><div className="title-row"><div><h1>{shelf.name}</h1><p className="lead">先确定基调，再让 AI 规划书或系列。</p></div><button className="primary" onClick={()=>setShow(!show)}>＋ 新的台阶</button></div>{show&&<PlanForm submit={onCreate}/>}<div className="series-grid">{shelf.series.map(s=><button className="series-card" key={s.id} onClick={()=>onOpen(s.id)}><span>系列</span><h2>{s.title}</h2><p>{s.rationale}</p><b>{s.progress}%</b></button>)}</div></section>}

function PlanForm({submit}:{submit:(b:object)=>Promise<void>}){const [topic,setTopic]=useState('Kubernetes'),[role,setRole]=useState('技术人员'),[experience,setExperience]=useState('熟悉 Linux、Docker 和基础网络，但没有实际使用过 K8s'),[purpose,setPurpose]=useState('即将参与基于 K8s 的应用部署与日常排障项目'),[depth,setDepth]=useState('deep');const send=async(e:FormEvent)=>{e.preventDefault();await submit({topic,role,experience,purpose,depth,details:'希望理解核心机制，而不只是记命令'})};return <form className="plan" onSubmit={send}><label>学习内容<input value={topic} onChange={e=>setTopic(e.target.value)}/></label><fieldset><legend>你的角色</legend>{['技术人员','产品或运营','管理人员','猎头或人力'].map(x=><button type="button" className={role===x?'selected':''} onClick={()=>setRole(x)} key={x}>{x}</button>)}</fieldset><label>相关经验<textarea value={experience} onChange={e=>setExperience(e.target.value)}/></label><label>学习目的<textarea value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><fieldset><legend>目标深度</legend>{[['overview','简单了解'],['deep','深度学习'],['mastery','掌握路径']].map(([v,l])=><button type="button" className={depth===v?'selected':''} onClick={()=>setDepth(v)} key={v}>{l}</button>)}</fieldset><button className="primary">生成目录方案</button></form>}

function SeriesPage({value,onChapter,onSection,onRefresh}:{value:Series;onChapter:(c:Chapter)=>void;onSection:(id:string)=>void;onRefresh:()=>Promise<void>}){const refresh=async(action:()=>Promise<unknown>)=>{try{await action();await onRefresh()}catch(e){window.alert(e instanceof Error?e.message:'操作失败')}};return <section><p className="eyebrow">系列进度 {value.progress}% · 已包含未来章节预计工作量</p><h1>{value.title}</h1><p className="lead">{value.rationale}</p>{value.books.map(book=><article className={`book ${book.status}`} key={book.id}><div className="book-head"><span>第 {book.position} 本</span><div><h2>{book.title}</h2><p>{book.description}</p></div><b>{book.progress}% · {Math.round(book.estimatedMinutes/60)} 小时</b></div>{book.chapters.map(c=><div className="chapter" key={c.id}><div><span>{c.position}</span><div><b>{c.title}</b><small>{c.objective}</small>{!c.generated&&<button className="ask-link" onClick={()=>{const title=window.prompt('未来章节标题',c.title);if(title)refresh(()=>api.updateChapter(c.id,{title}))}}>调整未来章</button>}</div></div>{!c.generated?<button disabled={c.status==='locked'} onClick={()=>onChapter(c)}>{c.status==='locked'?'未解锁':'生成小节'}</button>:<><div className="section-list">{c.sections.map(s=><button disabled={s.status==='locked'} onClick={()=>onSection(s.id)} key={s.id}><span>{s.position}</span>{s.title}<i>{s.status==='completed'?'✓':s.status==='locked'?'锁定':'开始'}</i></button>)}</div>{c.practice&&<ArtifactSubmission kind="practice" id={c.id} status={c.practice.status} attachmentCount={c.practice.attachments.length} onSubmit={refresh}/>}</>}</div>)}<button onClick={()=>{const title=window.prompt('新增未来章节标题');if(title)refresh(()=>api.addChapter(book.id,{title,objective:'由学习者补充的未来学习目标'}))}}>＋ 新增未来章</button>{book.capstone&&<ArtifactSubmission kind="capstone" id={book.id} status={book.capstone.status} attachmentCount={book.capstone.attachments.length} onSubmit={refresh}/>}</article>)}</section>}

function ArtifactSubmission({kind,id,status,attachmentCount,onSubmit}:{kind:'practice'|'capstone';id:string;status:string;attachmentCount:number;onSubmit:(action:()=>Promise<unknown>)=>Promise<void>}){const label=kind==='practice'?'章末实践':'全书大作业';const needsLegacyFile=status==='completed'&&attachmentCount===0;const enabled=status==='available'||needsLegacyFile;const upload=async(file:File)=>{const attachment=kind==='practice'?await api.uploadPractice(id,file):await api.uploadCapstone(id,file);return kind==='practice'?api.practice(id,{evidence:'由学习者提交',reflection:'已完成章末实践'},[attachment.id]):api.capstone(id,{artifact:'全书综合成果',verification:'学习者复核记录'},[attachment.id])};return <label className={kind==='capstone'?'primary':''}>{label}：{needsLegacyFile?'补充真实附件':status==='completed'?'已完成':status==='locked'?'未解锁':'选择成果文件'}<input type="file" hidden disabled={!enabled} onChange={event=>{const file=event.target.files?.[0];if(file)onSubmit(()=>upload(file))}}/></label>}

function Reader({value,onChange,onBack}:{value:Section;onChange:(s:Section)=>void;onBack:()=>void}){
  const [tab,setTab]=useState<'content'|'note'|'quiz'|'askme'>(value.status==='completed'?'note':'content');
  const [thread,setThread]=useState<string|undefined>(),[newQuestion,setNewQuestion]=useState(false),[selectedBlock,setSelectedBlock]=useState(value.content?.blocks[0]?.id||''),[answer,setAnswer]=useState('');
  const [qa,setQa]=useState<{q:string;a:string;relation:string}[]>([]),[answers,setAnswers]=useState<number[][]>(value.quiz?.questions.map(()=>[])||[]),[result,setResult]=useState<any>(),[askMe,setAskMe]=useState<import('./model/types').AskMe|null>(null),[oralAnswer,setOralAnswer]=useState('');
  const reload=async()=>{const next=await api.section(value.id);onChange(next);return next};
  const retryGeneration=async()=>{const next=await api.generateSection(value.id);onChange(next);setSelectedBlock(next.content?.blocks[0]?.id||'')};
  const ask=async()=>{if(!answer||!selectedBlock)return;const r=await api.ask(value.id,selectedBlock,answer,newQuestion?undefined:thread,newQuestion?'new_question':undefined);setThread(r.threadId);setQa([...qa,{q:answer,a:r.answer,relation:r.relation}]);setAnswer('');setNewQuestion(false)};
  const submit=async()=>{if(!value.quiz)return;const r=await api.quiz(value.id,value.quiz.id,answers);setResult(r);const next=await reload();setAnswers(next.quiz?.questions.map(()=>[])||[]);if(r.passed)setTab('note')};
  const runAskMe=async()=>{const next=await api.askMe(value.id,oralAnswer);setAskMe(next);setOralAnswer('')};
  return <div className="workspace"><aside><button onClick={onBack}>← 返回目录</button><p className="eyebrow">第 {value.position} 节</p><h2>{value.title}</h2><p>{value.question}</p>{value.generation&&<small>生成 #{value.generation.attempt}：{value.generation.status}{value.generation.error&&` · ${value.generation.error}`}</small>}<nav><button onClick={()=>setTab('content')}>正文</button><button disabled={!value.note} onClick={()=>setTab('note')}>我的笔记</button><button onClick={()=>setTab('quiz')}>验证</button><button disabled={!value.askMeUnlocked} onClick={()=>setTab('askme')}>Ask Me</button></nav></aside><article className="reading">
    {tab==='content'&&<>{!value.content&&<div className="error"><p>{value.generation?.error||'正文尚未生成。'}</p><button onClick={retryGeneration}>安全重试</button></div>}{value.content?.blocks.map(b=><section className={`block ${b.role}`} key={b.id}><small>{b.role} · {b.id}</small><h2>{b.heading}</h2><pre className={b.kind==='code'?'code':''}>{b.content}</pre><button className="ask-link" onClick={()=>setSelectedBlock(b.id)}>以此段为答疑锚点</button></section>)}{value.content&&<details><summary>已核验来源</summary>{value.content.sources.map((source,index)=><p key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> · {source.version} · {value.content?.sourceVerification[index]?.reachable?'服务端可达':'核验失败'}</p>)}</details>}</>}
    {tab==='note'&&<Note sectionId={value.id} note={value.note} onSaved={reload}/>} 
    {tab==='quiz'&&<div><h1>小节验证</h1>{value.remediations.map(item=><section className="block boundary" key={item.id}><small>错题补充教学 · {item.objectives.join('、')}</small>{item.blocks.map(block=><div key={block.id}><h3>{block.heading}</h3><pre>{block.content}</pre></div>)}</section>)}{value.quiz?.questions.map((q,i)=><fieldset className="question" key={`${value.quiz?.id}-${i}`}><legend>{i+1}. {q.prompt}{q.core&&<em>核心题</em>}</legend>{q.options.map((o,j)=><label key={j}><input type="checkbox" checked={answers[i]?.includes(j)} onChange={e=>setAnswers(a=>a.map((x,k)=>k===i?(e.target.checked?[...x,j]:x.filter(v=>v!==j)):x))}/>{o}</label>)}</fieldset>)}<button className="primary" onClick={submit}>提交验证</button>{result&&<p className={result.passed?'success':'error'}>{result.passed?'通过，笔记已经生成。':'未通过：补充教学已持久化，并换成实质不同的新题。'}</p>}</div>}
    {tab==='askme'&&<div><p className="eyebrow">满分隐藏关卡 · 机制 → 边界 → 迁移</p><h1>Ask Me</h1>{!askMe?<button className="primary" onClick={runAskMe}>开始三轮口试</button>:<>{askMe.entries.map(entry=><section key={entry.dimension}><b>{entry.dimension}</b><p>{entry.prompt}</p>{entry.answer&&<p>你的回答：{entry.answer} · 评估：{entry.evaluation}</p>}</section>)}{askMe.status!=='completed'?<><textarea value={oralAnswer} onChange={e=>setOralAnswer(e.target.value)} placeholder="只作答；考核过程中不会继续教学"/><button className="primary" onClick={runAskMe}>提交本轮</button></>:<p className="success">三轮口试完成，证据已写入掌握画像。</p>}</>}</div>}
  </article><aside className="qa"><h3>本节答疑</h3><small>锚点：{selectedBlock||'请选择正文段落'}</small>{qa.map((x,i)=><div key={i}><b>你 · {x.relation==='follow_up'?'追问':'新问题'}</b><p>{x.q}</p><b>Slow</b><p>{x.a}</p></div>)}<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="引用一个段落，继续追问…"/><label><input type="checkbox" checked={newQuestion} onChange={e=>setNewQuestion(e.target.checked)}/> 这是一个新问题</label><button className="primary" onClick={ask}>提问</button></aside></div>
}

function Note({sectionId,note,onSaved}:{sectionId:string;note:Section['note'];onSaved:()=>Promise<Section>}){const [editing,setEditing]=useState(JSON.stringify(note?.userContent||{},null,2)),[message,setMessage]=useState('');if(!note)return null;const save=async()=>{try{await api.note(sectionId,JSON.parse(editing));await onSaved();setMessage('已保存；AI 笔记未被覆盖。')}catch(e){setMessage(e instanceof Error?e.message:'保存失败')}};return <div><p className="eyebrow">完成后的核心资产</p><h1>AI 整理笔记</h1><pre className="note">{JSON.stringify(note.aiContent,null,2)}</pre><h2>我的补充</h2><textarea value={editing} onChange={e=>setEditing(e.target.value)}/><button className="primary" onClick={save}>保存我的内容</button>{message&&<p>{message}</p>}</div>}
