from dataclasses import dataclass
from typing import AsyncIterator, Literal, Protocol
from .contracts import AskMeTurn, ClassifiedAnswer, GeneratedChapter, GeneratedLesson, GeneratedNote, GeneratedPlan, ReplannedBook


@dataclass(frozen=True)
class ProviderCapabilities:
    protocol: Literal["openai", "anthropic"]
    api_mode: Literal["responses", "chat_completions", "messages"]
    structured_output: bool
    streaming: bool
    reasoning_mode: Literal["optional", "required", "disabled"]


class AiPort(Protocol):
    capabilities: ProviderCapabilities
    def structured_trace(self) -> list[dict]: ...
    async def plan(self, request: dict, memory: list[dict]) -> GeneratedPlan: ...
    async def chapter(self, request: dict, memory: list[dict]) -> GeneratedChapter: ...
    async def lesson(self, request: dict, memory: list[dict], prior_questions: list[dict] | None = None) -> GeneratedLesson: ...
    async def answer(self, request: dict) -> ClassifiedAnswer: ...
    def answer_stream(self, request: dict) -> AsyncIterator[str]: ...
    async def note(self, request: dict) -> GeneratedNote: ...
    async def ask_me(self, request: dict) -> AskMeTurn: ...
    async def replan_book(self, request: dict, memory: list[dict]) -> ReplannedBook: ...
