from dataclasses import dataclass
from typing import AsyncIterator, Literal, Protocol
from .contracts import AskMeTurn, ClaimSupportReview, ClassifiedAnswer, GeneratedChapter, GeneratedContent, GeneratedLesson, GeneratedNote, GeneratedPlan, GeneratedQuiz, LessonAlignmentReview, ReplannedBook, TeachingBlueprint


@dataclass(frozen=True)
class ProviderCapabilities:
    protocol: Literal["openai", "anthropic"]
    api_mode: Literal["responses", "chat_completions", "messages"]
    structured_output: bool
    streaming: bool
    reasoning_mode: Literal["optional", "required", "disabled"]


class AiPort(Protocol):
    capabilities: ProviderCapabilities
    staged_lesson_generation: bool
    def structured_trace(self) -> list[dict]: ...
    async def plan(self, request: dict, memory: list[dict]) -> GeneratedPlan: ...
    async def chapter(self, request: dict, memory: list[dict]) -> GeneratedChapter: ...
    async def teaching_blueprint(self, request: dict, memory: list[dict]) -> TeachingBlueprint: ...
    async def lesson(self, request: dict, memory: list[dict], prior_questions: list[dict] | None = None) -> GeneratedLesson: ...
    async def lesson_content(self, request: dict, memory: list[dict], prior_questions: list[dict] | None = None) -> GeneratedContent: ...
    async def repair_lesson_sources(self, request: dict, memory: list[dict], content: GeneratedContent, failed_sources: list[dict], prior_questions: list[dict] | None = None) -> GeneratedContent: ...
    async def lesson_quiz(self, request: dict, content: GeneratedContent, prior_questions: list[dict] | None = None) -> GeneratedQuiz: ...
    async def review_lesson_alignment(self, request: dict, content: GeneratedContent, quiz: GeneratedQuiz) -> LessonAlignmentReview: ...
    async def review_source_claim(self, request: dict) -> ClaimSupportReview: ...
    async def answer(self, request: dict) -> ClassifiedAnswer: ...
    def answer_stream(self, request: dict) -> AsyncIterator[str]: ...
    async def note(self, request: dict) -> GeneratedNote: ...
    async def ask_me(self, request: dict) -> AskMeTurn: ...
    async def replan_book(self, request: dict, memory: list[dict]) -> ReplannedBook: ...
