#!/bin/sh
set -eu

deploy_root=${DEPLOY_ROOT:-/opt/slow}
compose_file="$deploy_root/compose.prod.yml"
demo_compose_override="$deploy_root/compose.demo.yml"
https_compose_override="$deploy_root/compose.https.yml"
release_file="$deploy_root/.release"
release_env="$deploy_root/.release.env"
runtime_env="$deploy_root/.env"
builds_root="$deploy_root/builds"
database_authority_file="$deploy_root/data/database-authority"
cutover_script="$deploy_root/cutover-sqlite-to-postgres.sh"
rollback_override="$deploy_root/compose.sqlite-rollback.yml"

: "${APP_VERSION:?APP_VERSION is required}"
: "${IMAGE_NAME:?IMAGE_NAME is required}"
: "${WEB_ORIGIN:?WEB_ORIGIN is required}"
source_archive=${SOURCE_ARCHIVE:-"$deploy_root/slow-$APP_VERSION.tar.gz"}
REGISTRY=${REGISTRY:-ghcr.io}
PIP_INDEX_URL=${PIP_INDEX_URL:-https://mirrors.aliyun.com/pypi/simple/}
PNPM_REGISTRY=${PNPM_REGISTRY:-https://registry.npmmirror.com}
DEPLOY_MODE=${DEPLOY_MODE:-demo}

case "$DEPLOY_MODE" in
  demo|production) ;;
  *)
    echo "DEPLOY_MODE must be 'demo' or 'production'." >&2
    exit 1
    ;;
esac

cd "$deploy_root"

if [ ! -f .env ]; then
  echo "Missing $deploy_root/.env" >&2
  exit 1
fi
database_authority=""
if [ -f "$database_authority_file" ]; then
  database_authority=$(sed -n '1p' "$database_authority_file")
fi
cutover_required=false
case "$database_authority" in
  postgresql)
    ;;
  ""|sqlite)
    if [ "$DEPLOY_MODE" != "demo" ]; then
      echo "PostgreSQL is not the recorded database authority; run the documented SQLite cutover first." >&2
      exit 1
    fi
    cutover_required=true
    ;;
  *)
    echo "Unknown database authority '$database_authority'; refusing deployment." >&2
    exit 1
    ;;
esac
if [ ! -f "$source_archive" ]; then
  echo "Missing release source archive: $source_archive" >&2
  exit 1
fi
if [ "$DEPLOY_MODE" = "production" ] && [ ! -f "$https_compose_override" ]; then
  echo "Missing production HTTPS compose override: $https_compose_override" >&2
  exit 1
fi

mkdir -p "$builds_root" "$deploy_root/data/backups"
build_root=$(mktemp -d "$builds_root/${APP_VERSION}.XXXXXX")
tar -xzf "$source_archive" -C "$build_root"

source_root="$build_root"
if [ ! -f "$source_root/deploy/docker/api.Dockerfile" ]; then
  source_root=$(find "$build_root" -mindepth 1 -maxdepth 1 -type d -print -quit)
fi
if [ -z "$source_root" ] || [ ! -f "$source_root/deploy/docker/api.Dockerfile" ]; then
  echo "Release archive does not contain the expected project layout." >&2
  exit 1
fi

if [ "$cutover_required" = true ]; then
  bundled_cutover_script="$source_root/deploy/scripts/cutover-sqlite-to-postgres.sh"
  bundled_compose_file="$source_root/deploy/compose.prod.yml"
  bundled_demo_compose_override="$source_root/deploy/compose.demo.yml"
  bundled_rollback_override="$source_root/deploy/compose.sqlite-rollback.yml"
  for bundled_file in \
    "$bundled_cutover_script" \
    "$bundled_compose_file" \
    "$bundled_demo_compose_override" \
    "$bundled_rollback_override"; do
    if [ ! -f "$bundled_file" ]; then
      echo "Release archive is missing a demo cutover prerequisite: $bundled_file" >&2
      exit 1
    fi
  done
  install -m 700 "$bundled_cutover_script" "$cutover_script"
  install -m 600 "$bundled_compose_file" "$compose_file"
  install -m 600 "$bundled_demo_compose_override" "$demo_compose_override"
  install -m 600 "$bundled_rollback_override" "$rollback_override"
fi

docker build \
  --build-arg "PIP_INDEX_URL=$PIP_INDEX_URL" \
  -f "$source_root/deploy/docker/api.Dockerfile" \
  -t "$REGISTRY/$IMAGE_NAME-api:$APP_VERSION" \
  "$source_root"
docker build \
  --build-arg "PNPM_REGISTRY=$PNPM_REGISTRY" \
  -f "$source_root/deploy/docker/web.Dockerfile" \
  -t "$REGISTRY/$IMAGE_NAME-web:$APP_VERSION" \
  "$source_root"

previous_release_env=""
if [ -f "$release_env" ]; then
  previous_release_env=$(mktemp "$deploy_root/.release.env.previous.XXXXXX")
  cp "$release_env" "$previous_release_env"
fi

cleanup_previous_release_env() {
  if [ -n "$previous_release_env" ]; then
    rm -f "$previous_release_env"
  fi
}
trap cleanup_previous_release_env EXIT HUP INT TERM

compose() {
  if [ "$DEPLOY_MODE" = "demo" ]; then
    docker compose --env-file "$runtime_env" --env-file "$release_env" \
      -f "$compose_file" -f "$demo_compose_override" "$@"
  else
    docker compose --env-file "$runtime_env" --env-file "$release_env" \
      -f "$compose_file" -f "$https_compose_override" "$@"
  fi
}

log_failed_startup() {
  echo "Deployment startup diagnostics:" >&2
  compose ps -a >&2 || true
  compose logs --no-color --tail=200 db api web >&2 || true
}

restore_previous_release() {
  if [ -z "$previous_release_env" ]; then
    return 1
  fi
  cp "$previous_release_env" "$release_env"
  (
    set -a
    # The release file is generated by this script and contains only release variables.
    . "$release_env"
    set +a
    compose up -d --remove-orphans --force-recreate db api web
  )
}

restore_previous_sqlite_release() {
  if [ -z "$previous_release_env" ]; then
    return 1
  fi
  cp "$previous_release_env" "$release_env"
  docker compose --env-file "$runtime_env" --env-file "$release_env" \
    -f "$compose_file" -f "$rollback_override" -f "$demo_compose_override" \
    up -d --remove-orphans --force-recreate db api web
}

ensure_demo_postgres_password() {
  if grep -Eq '^POSTGRES_PASSWORD=.+$' "$runtime_env"; then
    return
  fi
  postgres_password=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
  runtime_env_next=$(mktemp "$deploy_root/.env.next.XXXXXX")
  cat "$runtime_env" > "$runtime_env_next"
  printf '\nPOSTGRES_PASSWORD=%s\n' "$postgres_password" >> "$runtime_env_next"
  chmod 600 "$runtime_env_next"
  mv "$runtime_env_next" "$runtime_env"
  unset postgres_password
  echo "Generated a server-local PostgreSQL password for the demo cutover."
}

if [ "$cutover_required" = true ]; then
  if [ ! -x "$cutover_script" ]; then
    echo "Missing executable demo cutover script: $cutover_script" >&2
    exit 1
  fi
  ensure_demo_postgres_password
fi

if [ "$cutover_required" = false ] && [ -f "$release_env" ] && \
   compose ps -q db 2>/dev/null | grep -q .; then
  backup_timestamp=$(date -u +%Y%m%dT%H%M%SZ)
  backup_file="$deploy_root/data/backups/slow-$backup_timestamp.dump"
  backup_next="$backup_file.next"
  compose exec -T db sh -c \
    'exec pg_dump --username="$POSTGRES_USER" --dbname="$POSTGRES_DB" --format=custom' \
    > "$backup_next"
  if [ ! -s "$backup_next" ] || ! compose exec -T db pg_restore --list < "$backup_next" >/dev/null; then
    rm -f "$backup_next"
    echo "PostgreSQL backup validation failed; deployment stopped." >&2
    exit 1
  fi
  mv "$backup_next" "$backup_file"
fi

release_env_next=$(mktemp "$deploy_root/.release.env.next.XXXXXX")
cat > "$release_env_next" <<EOF
REGISTRY=$REGISTRY
IMAGE_NAME=$IMAGE_NAME
APP_VERSION=$APP_VERSION
WEB_ORIGIN=$WEB_ORIGIN
EOF
mv "$release_env_next" "$release_env"

cutover_completed=false
if [ "$cutover_required" = true ]; then
  if ! DEPLOY_MODE="$DEPLOY_MODE" "$cutover_script"; then
    if [ -n "$previous_release_env" ]; then
      restore_previous_sqlite_release
      rm -f "$previous_release_env"
    fi
    echo "Demo PostgreSQL cutover failed; restored the previous SQLite release." >&2
    exit 1
  fi
  cutover_completed=true
fi

if ! compose up -d --remove-orphans --force-recreate db api web; then
  log_failed_startup
  if [ "$cutover_completed" = true ]; then
    echo "PostgreSQL is authoritative; refusing to roll back to SQLite after container startup failure." >&2
  elif [ -n "$previous_release_env" ]; then
    restore_previous_release
  fi
  echo "Deployment failed while starting containers." >&2
  exit 1
fi

healthy=false
attempt=1
while [ "$attempt" -le 45 ]; do
  if curl --fail --silent --show-error http://127.0.0.1/api/health >/dev/null 2>&1; then
    healthy=true
    break
  fi
  sleep 2
  attempt=$((attempt + 1))
done

if [ "$healthy" != true ]; then
  log_failed_startup
  if [ "$cutover_completed" = true ]; then
    echo "PostgreSQL is authoritative; refusing to roll back to SQLite after health-check failure." >&2
  elif [ -n "$previous_release_env" ]; then
    restore_previous_release
    echo "Deployment failed health checks; restored the previous release." >&2
  else
    echo "Initial deployment failed health checks; no previous release exists." >&2
  fi
  exit 1
fi

printf '%s\n' "$APP_VERSION-$DEPLOY_MODE" > "$release_file"
find "$deploy_root/data/backups" -type f -name 'slow-*.dump' -mtime +14 -delete
docker image prune -f >/dev/null

rm -f "$source_archive"

echo "$DEPLOY_MODE deployment $APP_VERSION is healthy."
