#!/bin/sh
set -eu

deploy_root=${DEPLOY_ROOT:-/opt/slow}
compose_file="$deploy_root/compose.prod.yml"
demo_compose_override="$deploy_root/compose.demo.yml"
https_compose_override="$deploy_root/compose.https.yml"
release_file="$deploy_root/.release"
release_env="$deploy_root/.release.env"
runtime_env="$deploy_root/.env"
builds_root="$deploy_root/builds"
database_authority_file="$deploy_root/data/database-authority"

: "${APP_VERSION:?APP_VERSION is required}"
: "${IMAGE_NAME:?IMAGE_NAME is required}"
: "${WEB_ORIGIN:?WEB_ORIGIN is required}"
source_archive=${SOURCE_ARCHIVE:-"$deploy_root/slow-$APP_VERSION.tar.gz"}
REGISTRY=${REGISTRY:-ghcr.io}
PIP_INDEX_URL=${PIP_INDEX_URL:-https://mirrors.aliyun.com/pypi/simple/}
PNPM_REGISTRY=${PNPM_REGISTRY:-https://registry.npmmirror.com}
DEPLOY_MODE=${DEPLOY_MODE:-demo}

case "$DEPLOY_MODE" in
  demo|production) ;;
  *)
    echo "DEPLOY_MODE must be 'demo' or 'production'." >&2
    exit 1
    ;;
esac

cd "$deploy_root"

if [ ! -f .env ]; then
  echo "Missing $deploy_root/.env" >&2
  exit 1
fi
if [ ! -f "$database_authority_file" ] || \
   [ "$(sed -n '1p' "$database_authority_file")" != "postgresql" ]; then
  echo "PostgreSQL is not the recorded database authority; run the documented SQLite cutover first." >&2
  exit 1
fi
if [ ! -f "$source_archive" ]; then
  echo "Missing release source archive: $source_archive" >&2
  exit 1
fi
if [ "$DEPLOY_MODE" = "production" ] && [ ! -f "$https_compose_override" ]; then
  echo "Missing production HTTPS compose override: $https_compose_override" >&2
  exit 1
fi

mkdir -p "$builds_root" "$deploy_root/data/backups"
build_root=$(mktemp -d "$builds_root/${APP_VERSION}.XXXXXX")
tar -xzf "$source_archive" -C "$build_root"

source_root="$build_root"
if [ ! -f "$source_root/deploy/docker/api.Dockerfile" ]; then
  source_root=$(find "$build_root" -mindepth 1 -maxdepth 1 -type d -print -quit)
fi
if [ -z "$source_root" ] || [ ! -f "$source_root/deploy/docker/api.Dockerfile" ]; then
  echo "Release archive does not contain the expected project layout." >&2
  exit 1
fi

docker build \
  --build-arg "PIP_INDEX_URL=$PIP_INDEX_URL" \
  -f "$source_root/deploy/docker/api.Dockerfile" \
  -t "$REGISTRY/$IMAGE_NAME-api:$APP_VERSION" \
  "$source_root"
docker build \
  --build-arg "PNPM_REGISTRY=$PNPM_REGISTRY" \
  -f "$source_root/deploy/docker/web.Dockerfile" \
  -t "$REGISTRY/$IMAGE_NAME-web:$APP_VERSION" \
  "$source_root"

previous_release_env=""
if [ -f "$release_env" ]; then
  previous_release_env=$(mktemp "$deploy_root/.release.env.previous.XXXXXX")
  cp "$release_env" "$previous_release_env"
fi

compose() {
  if [ "$DEPLOY_MODE" = "demo" ]; then
    docker compose --env-file "$runtime_env" --env-file "$release_env" \
      -f "$compose_file" -f "$demo_compose_override" "$@"
  else
    docker compose --env-file "$runtime_env" --env-file "$release_env" \
      -f "$compose_file" -f "$https_compose_override" "$@"
  fi
}

restore_previous_release() {
  if [ -z "$previous_release_env" ]; then
    return 1
  fi
  cp "$previous_release_env" "$release_env"
  (
    set -a
    # The release file is generated by this script and contains only release variables.
    . "$release_env"
    set +a
    compose up -d --remove-orphans --force-recreate db api web
  )
}

if [ -f "$release_env" ] && compose ps -q db 2>/dev/null | grep -q .; then
  backup_timestamp=$(date -u +%Y%m%dT%H%M%SZ)
  backup_file="$deploy_root/data/backups/slow-$backup_timestamp.dump"
  backup_next="$backup_file.next"
  compose exec -T db sh -c \
    'exec pg_dump --username="$POSTGRES_USER" --dbname="$POSTGRES_DB" --format=custom' \
    > "$backup_next"
  if [ ! -s "$backup_next" ] || ! compose exec -T db pg_restore --list < "$backup_next" >/dev/null; then
    rm -f "$backup_next"
    echo "PostgreSQL backup validation failed; deployment stopped." >&2
    exit 1
  fi
  mv "$backup_next" "$backup_file"
fi

release_env_next=$(mktemp "$deploy_root/.release.env.next.XXXXXX")
cat > "$release_env_next" <<EOF
REGISTRY=$REGISTRY
IMAGE_NAME=$IMAGE_NAME
APP_VERSION=$APP_VERSION
WEB_ORIGIN=$WEB_ORIGIN
EOF
mv "$release_env_next" "$release_env"

if ! compose up -d --remove-orphans --force-recreate db api web; then
  if [ -n "$previous_release_env" ]; then
    restore_previous_release
  fi
  echo "Deployment failed while starting containers." >&2
  exit 1
fi

healthy=false
attempt=1
while [ "$attempt" -le 45 ]; do
  if curl --fail --silent --show-error http://127.0.0.1/api/health >/dev/null 2>&1; then
    healthy=true
    break
  fi
  sleep 2
  attempt=$((attempt + 1))
done

if [ "$healthy" != true ]; then
  compose logs --tail=120
  if [ -n "$previous_release_env" ]; then
    restore_previous_release
    echo "Deployment failed health checks; restored the previous release." >&2
  else
    echo "Initial deployment failed health checks; no previous release exists." >&2
  fi
  exit 1
fi

printf '%s\n' "$APP_VERSION-$DEPLOY_MODE" > "$release_file"
find "$deploy_root/data/backups" -type f -name 'slow-*.dump' -mtime +14 -delete
docker image prune -f >/dev/null

if [ -n "$previous_release_env" ]; then
  rm -f "$previous_release_env"
fi
rm -f "$source_archive"

echo "$DEPLOY_MODE deployment $APP_VERSION is healthy."
